# Numpy Basics
## Create an array of 10 elements.
1. Find the unique elements
2. Add 5 elements in array
3. Delete 2 elements
4. Update an element at position 3

## Create another array of 5 elements
1. Add two arrays
2. Append the arrays
3. Find the common elements between two arrays

## Create an array of order 5X5
1. Find the average of the 3rd column
2. Count number of non zero elements in 4th column
3. Find max and min values in the entire array
4. Print elements greater than 2 in second column
5. Find the  row having the max element



In [2]:
import numpy as np
arr1=np.array([1,2,3,3,4,6,7,8,9,10])
arr1

array([ 1,  2,  3,  3,  4,  6,  7,  8,  9, 10])

In [3]:
np.unique(arr1)

array([ 1,  2,  3,  4,  6,  7,  8,  9, 10])

In [10]:
x=np.array([11,20,50,30,2])
arr1=np.concatenate((arr1,x))
arr1

array([ 1,  2,  3,  3,  4,  6,  7,  8,  9, 10, 11, 20, 50, 30,  2])

In [14]:
# give indices to delete as second argument
arr1=np.delete(arr1,[2,5])

In [15]:
arr1[3]=100
arr1

array([  1,   2, 100, 100,   7,   8,   9,  10,  11,  20,  50,  30,   2])

In [16]:
arr2=np.array([101,102,103,104])
arr2

array([101, 102, 103, 104])

In [17]:
arr2=np.append(arr2,[10,20,30])
arr2

array([101, 102, 103, 104,  10,  20,  30])

In [18]:
# gives common elements in both arrays
np.intersect1d(arr1,arr2)

array([10, 20, 30])

In [46]:
# takes random integers from given range (1,10)--first argument
# shape 5X5 ---second argument
arr3=np.random.randint(1,10,(5,5))
arr3

array([[8, 7, 2, 9, 7],
       [3, 3, 6, 6, 7],
       [7, 4, 5, 9, 2],
       [1, 2, 1, 9, 2],
       [6, 6, 6, 8, 7]])

In [47]:
column3=arr3[:,2]
column3

array([2, 6, 5, 1, 6])

In [48]:
column3.mean()

4.0

In [49]:
non=np.nonzero(arr3[:,3])
len(non[0])

5

In [50]:
np.count_nonzero(arr3[:,3])

5

In [51]:
arr3.min()

1

In [52]:
arr3.max()

9

In [53]:
# where funtion returns the indices of places where the condition is satisfied
i=np.where(arr3[:,1]>2)
arr3[i,1]

array([[7, 3, 4, 6]])

In [54]:
ind=np.where(arr3==np.max(arr3))
print("Rows having max element are : ",ind[0])

Rows having max element are :  [0 2 3]
